### ISSUE TITLE
Update Team Role Popover

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#153]
When copying over member invite link at the bottom of the task modal, clicking member freezes the member modal on screen
Prevents you from closing the popover modal for that member

**Comment by ato1120** [comment]
I remember this bug but can't duplicate it now. Do we know that it's solved?

**Comment by dretelny** [comment]
it still happens. Not sure when. I think if you switch tabs or click on another role. It doesn’t always happen though but definitely does sometimes 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
