### ISSUE TITLE
Two events have the same ID

### ISSUE THREAD

**Issue by ofagbemi** [StanfordHCI/foundry#171]
I'm not totally sure why, but I ran into this in the console after logging `flashTeamsJSON.events`:

![xzsmkalksqgcgceg](https://cloud.githubusercontent.com/assets/6354033/5676184/3e251cac-9814-11e4-9b48-eae9f0eb090c.png)

**Comment by negarrahmati** [comment]
Did you just create two events and realized that this is the case or did something especial happen?

**Comment by ofagbemi** [comment]
I was just working in an old saved team I had and noticed this. I can try to reproduce it.

**Comment by negarrahmati** [comment]
Hmm. I cannot reproduce this. The ids are fine for me. Can you let me know if you encounter this bug again?

**Comment by ofagbemi** [comment]
Will do

On Sunday, January 11, 2015, Negar <notifications@github.com> wrote:

> Hmm. I cannot reproduce this. The ids are fine for me. Can you let me know
> if you encounter this bug again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StanfordHCI/foundry/issues/171#issuecomment-69479421>.
>


--

**Comment by ofagbemi** [comment]
So I was messing around and this came up again in a new flash team. Again, it happened with the id 6. I'll see if I can figure out what triggers it.

**Comment by ato1120** [comment]
Following up on this, this is creating render issues. The following team only has 3 displayed events, but 5 events in the json, 2 with the same id 4 and 6. When I left the team it looked as it does in the first screenshot. On reload the second renders. If you start to drag the events, the details come back as they were in the first screenshot. 
![screen shot 2015-01-24 at 12 33 53 am](https://cloud.githubusercontent.com/assets/1930207/5886682/b6db14ce-a360-11e4-98db-3aed4e4df0ea.png)

![screen shot 2015-01-24 at 12 34 01 am](https://cloud.githubusercontent.com/assets/1930207/5886683/b9724b62-a360-11e4-9431-3bc5aeebdf00.png)

**Comment by negarrahmati** [comment]
Did you create a new team or was it a duplicated team? Did you do anything
special that I should do while trying to reproduce this bug?

I am asking these questions because my previous efforts in reproducing the
bug was unsuccessful.

**Comment by ato1120** [comment]
Oh, good question! I think for me the issue always occurred on duplicated teams! I will follow-up if this is *not* the case.
