### ISSUE TITLE
You can't click on handoffs or collaborations

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#176]
It appears like you can only click on the latest one that was created. There is no way to make the popover appear on most of them (the mouse also doesn't change to a pointer unless you can click on it, which is with very few). This appears to be a new bug since introducing the new event blocks

**Comment by dretelny** [comment]
@ato1120 is this something you can look into?

**Comment by ato1120** [comment]
I'm seeing this on handoffs, but not collaborations. I don't think this is very new, we've been seeing the handoffs render behind some grid lines for a while now but I can definitely look into it. Can you confirm that it is an issue for collaborations? 

It's also not consistent. Clearly we want to address this, but can you also confirm if you can click everything after a refresh? So far I can.

**Comment by dretelny** [comment]
Yes, refreshing solves the problem. Interesting...

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Sent in a PR that fixes this, and one other small problem here
<https://github.com/StanfordHCI/foundry/pull/207>.

**Comment by ofagbemi** [comment]
I'll review this!

Alexandra To
---------------------------------------------------------------------
B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
Interaction (HCI)
Minor in Asian American Studies
Stanford University
Residential Computer Consultant (RCC) - Rains Z
BOSP Head Student Advisor
