### ISSUE TITLE
Member line on the event

### ISSUE THREAD

**Issue by negarrahmati** [StanfordHCI/foundry#180]
Deleting a member from an event doesn't hide the member line on the event until the page is refreshed.

**Comment by dretelny** [comment]
@ofagbemi is this something you can fix?

**Comment by dretelny** [comment]
@ofagbemi and @negarrahmati the member line also doesn't disappear from an event if you erase a member from a team completely (i.e. you delete them from the team roles section in the left sidebar)

**Comment by ofagbemi** [comment]
Sorry, forgot about this one. Just fixed what @dretelny mentioned, about to get on the other one.

[PR's up here](https://github.com/StanfordHCI/foundry/pull/194).

**Comment by ofagbemi** [comment]
@dretelny @negarrahmati Alright, fixed.

**Comment by ofagbemi** [comment]
Sorry, missed this one! Fixed!

PR's up here <https://github.com/StanfordHCI/foundry/pull/194>.

**Comment by negarrahmati** [comment]
Thanks Jare. I will merge it.

**Comment by dretelny** [comment]
Thanks so much, Jare! I just merged both. Negar, I had a few minutes so I figured I’d save you the work :) 

Will update both herokus now!

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
