### ISSUE TITLE
Time goes over the event 

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#182]
The background also gets cut off and creates a weird line to the right. See photo below: 

![image](https://cloud.githubusercontent.com/assets/5275384/5752446/2da62410-9c2a-11e4-952c-7b01a4643ada.png)

**Comment by dretelny** [comment]
@ofagbemi do you think this will take long to fix?

**Comment by ofagbemi** [comment]
Fixed. PR's up here <https://github.com/StanfordHCI/foundry/pull/189>.
