### ISSUE TITLE
The drag handlebars appear in the runtime mode

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#185]
Once the team is running, if you hover over the tasks (regardless of whether they haven't been started, are in progress, delayed, etc.), the drag handlebars appear, which makes it seem like the tasks can be resized even though they obviously can't.

**Comment by ofagbemi** [comment]
I'll get on this. Just really quickly, is there a way I can check the
runtime mode?

**Comment by dretelny** [comment]
Yes, you click on "start team" and then it should be in runtime mode. You can then click on start task to start the specific tasks.

**Comment by ofagbemi** [comment]
I want to make sure—when exactly can an event be edited? It looks like
right now it can be edited before the team starts and after you end the
team and refresh the page. Is that right?

I went ahead and sent a PR for the fix to this here
<https://github.com/StanfordHCI/foundry/pull/190>.

**Comment by dretelny** [comment]
That is correct! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
