### ISSUE TITLE
Weird line after the event block when task is delayed

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#195]
For some reason, when a task gets delayed, there is a weird line that appears to the right of the task. See screenshot below: 

![image](https://cloud.githubusercontent.com/assets/5275384/5788031/4614de84-9ddc-11e4-81cd-db628f35ecfa.png)

**Comment by dretelny** [comment]
@ofagbemi is this something you can fix?

**Comment by ofagbemi** [comment]
@dretelny It looks like that's being caused by some function called `drawRedBox` in `awareness.js`. I can't super tell what's going on. I'll just hide it for now.
