### ISSUE TITLE
Chat Bugs

### ISSUE THREAD

**Issue by negarrahmati** [StanfordHCI/foundry#225]
The time stamps are messed up.
The messages get duplicated.

See this project:
http://foundry-app.herokuapp.com/flash_teams/30/edit

**Comment by dretelny** [comment]
I think these issues are now fixed with my latest PR that you merged. Although we should double check the duplicate message situation. In my tests so far, I have not encountered any duplicate messages.

**Comment by ofagbemi** [comment]
Okay, I think it's good now. I just pulled in your changes and fixed the
duplication bug Negar was talking about—it just started showing up for me.

PR's up here <https://github.com/StanfordHCI/foundry/pull/224>.

**Comment by dretelny** [comment]
I’ll check it out, thanks! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
