### ISSUE TITLE
All handoffs are disappeared after deleting an event and refreshing the page.

### ISSUE THREAD

**Issue by negarrahmati** [StanfordHCI/foundry#238]

**Comment by dretelny** [comment]
I create a team and add handoffs:
![image](https://cloud.githubusercontent.com/assets/5275384/6221759/ca856804-b5fc-11e4-9455-260761691c08.png)

After deletion but before refresh: 
![image](https://cloud.githubusercontent.com/assets/5275384/6221765/e3bad6f6-b5fc-11e4-8f82-89fbcc5b7cfb.png)

After refresh: 
![image](https://cloud.githubusercontent.com/assets/5275384/6221767/eee0abb4-b5fc-11e4-8b26-ba472de1c84a.png)
