### ISSUE TITLE
ChildIds error in console

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#255]
See screenshot, @ofagbemi can you fix this?

![image](https://cloud.githubusercontent.com/assets/5275384/6331428/e273e440-bb33-11e4-8c02-d7e14195f85f.png)

**Comment by ofagbemi** [comment]
What led to that error? Can you reproduce it?

**Comment by dretelny** [comment]
It happens every time you load the page (there need to be events on the workflow). So create a team, add an event and then refresh the page and you should see it

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
I thought this was fixed but it is not so I'm reopening the issue

**Comment by ofagbemi** [comment]
Sorry, just saw this. Fixed it here
<https://github.com/StanfordHCI/foundry/pull/270>.
