### ISSUE TITLE
No indication of which email is open on the sidebar on hiring portal

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#29]
No indication of which email is open on the sidebar. Can we make the sidebar menu items 'active' maybe using the css from hover?

**Comment by ato1120** [comment]
This looks almost done. Implemented on the email type but not task type?

**Comment by dretelny** [comment]
@ato1120 I just fixed this and merged it myself (pull latest version of master to see the changes). All links on left sidebar should highlight properly now
