### ISSUE TITLE
Pause/Complete buttons don't disappear when task completed

### ISSUE THREAD

**Issue by ato1120** [StanfordHCI/foundry#340]
The sidebar and alert buttons don't go away when a user has completed their task. The sidebar text is correct, but the buttons should be gone. 

![screen shot 2015-05-28 at 3 01 12 pm](https://cloud.githubusercontent.com/assets/1930207/7872223/48104152-054b-11e5-985f-4e206ffc3a0f.png)

**Comment by ato1120** [comment]
Note: From what I can tell, this is only once the task has been delayed, THEN completed

**Comment by ato1120** [comment]
The alert is not relevant for a non-delayed task, as there is no alert that appears in that case.

**Comment by dretelny** [comment]
Was this before or after you merged my PR? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
Before, I checked the master branch after I noticed it on your PR.

Alexandra To
---------------------------------------------------------------------
B.S. '14, M.S. '15 Candidate in Symbolic Systems: Human-Computer
Interaction (HCI)
Minor in Asian American Studies
Stanford University
Residential Computer Consultant (RCC) - Rains Z
BOSP Head Student Advisor

**Comment by dretelny** [comment]
Oh ok, cool. Glad to know it wasn’t a new problem in my PR. 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
