### ISSUE TITLE
Task Redesign

### ISSUE THREAD

**Issue by ato1120** [StanfordHCI/foundry#43]
Open Questions: 
-How do we indicate/highlight a specific logged-in worker's tasks?
-How do we indicate the status of a task (not_started, started, delayed, complete)
-What is included in a task? Do we need to include "Upload" here?
-How are tasks drawn?

INCLUDE:
Title
Workers
Drag ends to resize
Drag task to move

**Comment by ofagbemi** [comment]
![screen shot 2015-01-02 at 9 22 33 pm](https://cloud.githubusercontent.com/assets/6354033/5601594/4c4d344e-92cf-11e4-806d-4f7a9738f22b.png)

![screen shot 2015-01-02 at 9 15 08 pm](https://cloud.githubusercontent.com/assets/6354033/5601595/5ec65786-92cf-11e4-84ec-c4e7e8999c89.png)
