### ISSUE TITLE
Show the handoff behind the events

### ISSUE THREAD

**Issue by negarrahmati** [StanfordHCI/foundry#70]

**Comment by ato1120** [comment]
Jare, can you change the order of the svgs so that the handoffs are behind the events (but still on top of the timeline)? 

@dretelny @negarrahmati we still want this right? Jare just created each item in different layers but handoffs and collabs are on top.

**Comment by ofagbemi** [comment]
Just realized I actually put the layers in random order haha. Fixed that
and did this. A note, though—doing this means the line that shows up when
you're actually creating the handoff is also behind the events:

[image: Inline image 1]

Is this what you want?

**Comment by dretelny** [comment]
Sounds good to me!
