### ISSUE TITLE
The alignment for "total runtime" on task modal is slightly off 

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#84]
See photo

![image](https://cloud.githubusercontent.com/assets/5275384/5110404/54007a40-6fcd-11e4-8e8a-b14eb4c6f549.png)

**Comment by ato1120** [comment]
Not that it makes a big difference, but I think it's actually the DRI, not the Total Runtime that is off. If you don't add much info you can see it in the Left column and it is off.
![screen shot 2015-01-12 at 11 12 56 pm](https://cloud.githubusercontent.com/assets/1930207/5717163/a50ac1bc-9ab0-11e4-97b6-f522952a95d4.png)

**Comment by dretelny** [comment]
Yea, it’s the way the divs and spans are done but I would imagine that Ishita will resolve this when she redesigns the modals…
 
Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>
