### ISSUE TITLE
Worker task status info in sidebar no longer appears

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#9]
The blue text with worker's task info in sidebar under "Welcome, [worker name]!" no longer appears. See attached screenshot. 

![image](https://cloud.githubusercontent.com/assets/5275384/4172943/7fca301e-3551-11e4-85e5-779a9dd08203.png)

**Comment by dretelny** [comment]
@ato1120 why did you close this? it's not fixed yet?

**Comment by ato1120** [comment]
Ah, sorry, I read that just saying the name didn't appear and I remember someone fixing that, reopened!

**Comment by ato1120** [comment]
@dretelny This is done now, right?

**Comment by dretelny** [comment]
Yea, the one thing that might be nice to have since we removed the project status bar is a message that says "the team hasn't started yet" but I suppose that's outside of the scope of this issue so yes, close it :)
